import mongoose from 'mongoose';

const DeviceSchema = new mongoose.Schema({
  userId: String,
  deviceType: String,
  'Computer Name': String,
  'Operating System': String,
  'Computer Make': String,
  'Computer Model Number': String,
  'Serial Number': String,
  'Processor Type': String,
  'Processor Speed': String,
  'RAM Type': String,
  'RAM Size': String,
  'Hard Drive Size': String,
  'SSD': Boolean,
  'Optical Device': Boolean,
  'Bluetooth': Boolean,
  'Wifi': Boolean,
  'Camera': Boolean,
  'Card Reader': Boolean,
  'Fingerprint Reader': Boolean,
  'Mini/Micro USB': Boolean,
  'Thunderbolt': Boolean,
  'HDMI': Boolean,
  'DisplayPort': Boolean,
  'Mini DisplayPort': Boolean,
  'Public IP': String,
  'Private IP': String,
  'Purchase Price': String,
  'Date of Purchases': Date,
  'Monitor Make': String,
  'Monitor Model Number': String,
  'Monitor Serial Number': String,
  'Monitor Purchase Price': String,
  'Username': String,
  'Password': String,
  'Make': String,
  'Model Number': String,
  'Phone Number': String,
  'End User': String,
  'Carrier': String,
  'Customer Service Phone Number': String,
  'Issue Date': Date,
  'Name': String,
  'Make': String,
  'Model': String,
  'Express Service Code': String,
  'IP Address': String,
  'Subnet Mask': String,
  'Gateway': String,
  'DNS Server': String,
  'Location': String,
  'WEP Key': String,
  'Network Share Name': String,
  'Black Ink Replacement Type': String,
  'Color Ink Replacement Type': String,
  'Wireless Network Password': String,
  'Lan IP': String,
  'Wan IP': String,
  'Equipment Type': String,
  'Was it provided an IP?': Boolean,
  'Wireless?': Boolean,
});

export default mongoose.model('Device', DeviceSchema);
