import mongoose from 'mongoose';

const ServiceSchema = new mongoose.Schema({
  userId: String,
  serviceType: String,
  creationDate: Date,
  // _id: { type: Schema.Types.ObjectId, unique: true },
  'Software Name': String,
  'Computer/Server Name': String,
  'File Location/Path': String,
  'Login ID': String,
  'Login Password': String,
  'IP Address of Server': String,
  'Admin Username': String,
  'Admin Password': String,
  'Database Name': String,
  'Application Name': String,
  'URL Server Can Be Located': String,
  'Security Question #1': String,
  'Security Answer #1': String,
  'Security Question #2': String,
  'Security Answer #2': String,
  'Web Mail URL': String,
  'Email Address': String,
  'Password': String,
  'Name of Company': String,
  'Incoming SMTP Server Address': String,
  'Outgoing SMTP Server Address': String,
  'Description': String,
  'SSL?': Boolean,
  'Server Authorization?': Boolean,
  'Service Date': Date,
  'Tech Support Vendor': String,
  'Technician Name': String,
  'Case Number': String,
  'Problem Description': String,
  'Provider Name': String,
  'Main Account Email': String,
  'Main Account Password': String,
  'Vendor Phone Number': String,
  'Subnet Mask': String,
  'WAN IP Adddress': String,
  'URL': String,
  'DNS Server 1': String,
  'DNS Server 2': String,
  'Static IP Adddresses': String,
  'Software Name': String,
  'Software License Key': String,
  'Number of Licenses Purchased': String,
  'Purchase Price': String,
  'Purchase Date': String,
  'Computer Name': String,
  'Incident ID': String,
  'Phone Number': String,
  'Date of Incident': Date,
  'Name': String,
  'Email': String,
  'Company Name': String,
  'PIN': String,
  'Upgrade Date': Date,
  'Warranty Start Date': Date,
  'Warranty End Date': Date,
  'Extended?': Boolean,
  'Admin Username': String,
  'Admin Password': String,
  'Domain Name': String,
  'Hosting Company': String,
  'Admin Name': String,
  'Admin Email': String,
  'Admin Phone Number': String,
  'Passcode': String,
});


export default mongoose.model('Service', ServiceSchema);
