const labels = {
  computer1: {
    text: [
      'Computer Name',
      'Operating System',
      'Computer Make',
      'Computer Model Number',
      'Serial Number',
    ],
  },
  computer2: {
    text: [
      'Processor Type',
      'Processor Speed',
      'RAM Type',
      'RAM Size',
      'Hard Drive Size',
      'SSD?',
    ],
  },
  computer3: {
    check: [
      'Optical Device',
      'Bluetooth',
      'Wifi',
      'Camera',
      'Card Reader',
      'Fingerprint Reader',
      'Mini/Micro USB',
      'Thunderbolt',
      'HDMI',
      'DisplayPort',
      'Mini DisplayPort',
    ],
  },
  computer4: {
    text: ['Public IP', 'Private IP', 'Purchase Price'],
    date: ['Date of Purchases'],
  },
  computer5: {
    text: [
      'Monitor Make',
      'Monitor Model #',
      'Monitor Serial #',
      'Monitor Purchase Price',
    ],
  },
  computer6: {
    text: ['Username', 'Password'],
  },
  phone1: {
    text: [
      'Make',
      'Model',
      'Serial Number',
      'Phone Number',
      'End User',
      'Carrier',
      'Customer Service Phone Number',
      'Public IP',
      'Private IP',
    ],
    date: ['Issue Date'],
  },
  tablet1: {
    text: [
      'Make',
      'Model',
      'Serial Number',
      'Phone Number',
      'End User',
      'Carrier',
      'Customer Service Phone Number',
      'Public IP',
      'Private IP',
    ],
    date: ['Issue Date'],
  },
  printer1: {
    text: [
      'Name',
      'Make',
      'Model',
      'Serial Number',
      'Express Service Code',
      'IP Address',
      'Subnet Mask',
      'Gateway',
      'DNS Server',
      'Location',
      'WEP Key',
      'Network Share Name',
      'Black Ink Replacement Type',
      'Color Ink Replacement Type',
      'Purchase Price',
      'Public IP',
      'Private IP',
    ],
    date: ['Purchase Date'],
  },
  router1: {
    text: [
      'Wireless Network Password',
      'Make',
      'Model',
      'Serial Number',
      'Lan IP',
      'Wan IP',
      'DNS',
      'WEP Key',
      'Defualt Gateway',
      'Subnet Mask',
      'Network Share Name',
      'Equipment Type',
      'Username',
      'Password',
      'Purchase Price',
      'Location',
    ],
    check: ['Was it provided an IP?', 'Wireless?'],
    date: ['Purchase Date'],
  },
};

export default labels;
